# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Login.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LoginWindow(object):
    def setupUi(self, LoginWindow):
        LoginWindow.setObjectName("LoginWindow")
        LoginWindow.resize(800, 600)
        LoginWindow.setIconSize(QtCore.QSize(28, 28))
        self.centralwidget = QtWidgets.QWidget(LoginWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(50, 50, 321, 471))
        self.frame.setStyleSheet("#frame{\n"
"background-color: qlineargradient(spread:pad, x1:1, y1:0, x2:1, y2:1, stop:0 rgba(255, 255, 255, 255), stop:1 rgba(0, 0, 0, 255));\n"
"border-radius:20px;\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(20, 110, 271, 61))
        self.label.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 25pt \"方正粗黑宋简体\";")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(24, 160, 261, 51))
        self.label_2.setStyleSheet("font: 12pt \"Georgia\";\n"
"color: rgb(255, 255, 255);")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(120, 310, 81, 31))
        self.label_3.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 14pt \"幼圆\";\n"
"")
        self.label_3.setObjectName("label_3")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(370, 60, 321, 451))
        self.frame_2.setStyleSheet("#frame_2{\n"
"    background-color: rgb(255, 255, 255);\n"
"    border-top-right-radius:20px;\n"
"    border-bottom-right-radius:20px;\n"
"}")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.close_bt = QtWidgets.QPushButton(self.frame_2)
        self.close_bt.setGeometry(QtCore.QRect(280, 7, 31, 31))
        self.close_bt.setStyleSheet("QPushButton{\n"
"    border:none;\n"
"}\n"
"QPushButton:hover{\n"
"    padding-bottom:6px;\n"
"}")
        self.close_bt.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../logo_imgs/LogIcon/close.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.close_bt.setIcon(icon)
        self.close_bt.setIconSize(QtCore.QSize(24, 24))
        self.close_bt.setObjectName("close_bt")
        self.frame_3 = QtWidgets.QFrame(self.frame_2)
        self.frame_3.setGeometry(QtCore.QRect(0, 30, 321, 411))
        self.frame_3.setMinimumSize(QtCore.QSize(321, 411))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_4 = QtWidgets.QFrame(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(8)
        sizePolicy.setHeightForWidth(self.frame_4.sizePolicy().hasHeightForWidth())
        self.frame_4.setSizePolicy(sizePolicy)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame_6 = QtWidgets.QFrame(self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(5)
        sizePolicy.setHeightForWidth(self.frame_6.sizePolicy().hasHeightForWidth())
        self.frame_6.setSizePolicy(sizePolicy)
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_6)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.stackedWidget_2 = QtWidgets.QStackedWidget(self.frame_6)
        self.stackedWidget_2.setStyleSheet("QLineEdit{\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    border:none;\n"
"    border-bottom:1px solid black;\n"
"}\n"
"QPushButton{\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(0, 0, 0);\n"
"    border-radius:7px;\n"
"}\n"
"QPushButton:pressed{\n"
"    padding-top:5px;\n"
"    padding-left:5px;\n"
"}")
        self.stackedWidget_2.setObjectName("stackedWidget_2")
        self.page_login = QtWidgets.QWidget()
        self.page_login.setObjectName("page_login")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.page_login)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.lineEdit_logUser = QtWidgets.QLineEdit(self.page_login)
        self.lineEdit_logUser.setMinimumSize(QtCore.QSize(0, 35))
        self.lineEdit_logUser.setObjectName("lineEdit_logUser")
        self.verticalLayout_5.addWidget(self.lineEdit_logUser)
        self.lineEdit_LogPasssword = QtWidgets.QLineEdit(self.page_login)
        self.lineEdit_LogPasssword.setMinimumSize(QtCore.QSize(0, 35))
        self.lineEdit_LogPasssword.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_LogPasssword.setObjectName("lineEdit_LogPasssword")
        self.verticalLayout_5.addWidget(self.lineEdit_LogPasssword)
        self.login_bt2 = QtWidgets.QPushButton(self.page_login)
        self.login_bt2.setMinimumSize(QtCore.QSize(0, 40))
        self.login_bt2.setStyleSheet("font: 14pt \"黑体\";")
        self.login_bt2.setObjectName("login_bt2")
        self.verticalLayout_5.addWidget(self.login_bt2)
        self.stackedWidget_2.addWidget(self.page_login)
        self.page_register = QtWidgets.QWidget()
        self.page_register.setObjectName("page_register")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.page_register)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.lineEdit_ResUser = QtWidgets.QLineEdit(self.page_register)
        self.lineEdit_ResUser.setMinimumSize(QtCore.QSize(0, 35))
        self.lineEdit_ResUser.setObjectName("lineEdit_ResUser")
        self.verticalLayout_6.addWidget(self.lineEdit_ResUser)
        self.lineEdit_ResPassword = QtWidgets.QLineEdit(self.page_register)
        self.lineEdit_ResPassword.setMinimumSize(QtCore.QSize(0, 35))
        self.lineEdit_ResPassword.setObjectName("lineEdit_ResPassword")
        self.verticalLayout_6.addWidget(self.lineEdit_ResPassword)
        self.lineEdit_Respassword2 = QtWidgets.QLineEdit(self.page_register)
        self.lineEdit_Respassword2.setMinimumSize(QtCore.QSize(0, 35))
        self.lineEdit_Respassword2.setObjectName("lineEdit_Respassword2")
        self.verticalLayout_6.addWidget(self.lineEdit_Respassword2)
        self.register_bt2 = QtWidgets.QPushButton(self.page_register)
        self.register_bt2.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setFamily("方正粗黑宋简体")
        font.setPointSize(13)
        self.register_bt2.setFont(font)
        self.register_bt2.setToolTipDuration(-1)
        self.register_bt2.setObjectName("register_bt2")
        self.verticalLayout_6.addWidget(self.register_bt2)
        self.stackedWidget_2.addWidget(self.page_register)
        self.verticalLayout_4.addWidget(self.stackedWidget_2)
        self.verticalLayout_3.addWidget(self.frame_6)
        self.frame_7 = QtWidgets.QFrame(self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.frame_7.sizePolicy().hasHeightForWidth())
        self.frame_7.setSizePolicy(sizePolicy)
        self.frame_7.setStyleSheet("QPushButton{\n"
"    border:none;\n"
"}\n"
"QPushButton:pressed{\n"
"    padding-top:5px;\n"
"    padding-left:5px;\n"
"}")
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_7)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.login_bt = QtWidgets.QPushButton(self.frame_7)
        self.login_bt.setToolTipDuration(-1)
        self.login_bt.setStyleSheet("font: 9pt \"Bahnschrift\";")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../logo_imgs/LogIcon/login.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.login_bt.setIcon(icon1)
        self.login_bt.setIconSize(QtCore.QSize(24, 24))
        self.login_bt.setObjectName("login_bt")
        self.horizontalLayout.addWidget(self.login_bt)
        self.register_bt = QtWidgets.QPushButton(self.frame_7)
        self.register_bt.setStyleSheet("font: 9pt \"Bahnschrift\";")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../logo_imgs/LogIcon/register.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.register_bt.setIcon(icon2)
        self.register_bt.setIconSize(QtCore.QSize(24, 24))
        self.register_bt.setObjectName("register_bt")
        self.horizontalLayout.addWidget(self.register_bt)
        self.verticalLayout_3.addWidget(self.frame_7)
        self.verticalLayout.addWidget(self.frame_4)
        self.frame_5 = QtWidgets.QFrame(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.frame_5.sizePolicy().hasHeightForWidth())
        self.frame_5.setSizePolicy(sizePolicy)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_5)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.stackedWidget = QtWidgets.QStackedWidget(self.frame_5)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.stackedWidget.addWidget(self.page_2)
        self.verticalLayout_2.addWidget(self.stackedWidget)
        self.verticalLayout.addWidget(self.frame_5)
        self.frame_2.raise_()
        self.frame.raise_()
        LoginWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(LoginWindow)
        self.stackedWidget_2.setCurrentIndex(0)
        self.close_bt.clicked.connect(LoginWindow.close)
        QtCore.QMetaObject.connectSlotsByName(LoginWindow)

    def retranslateUi(self, LoginWindow):
        _translate = QtCore.QCoreApplication.translate
        LoginWindow.setWindowTitle(_translate("LoginWindow", "MainWindow"))
        self.label.setText(_translate("LoginWindow", "人脸识别考勤系统"))
        self.label_2.setText(_translate("LoginWindow", "Face Recognition Attendance System"))
        self.label_3.setText(_translate("LoginWindow", "欢迎登录"))
        self.lineEdit_logUser.setPlaceholderText(_translate("LoginWindow", "账号"))
        self.lineEdit_LogPasssword.setPlaceholderText(_translate("LoginWindow", "密码"))
        self.login_bt2.setText(_translate("LoginWindow", "登录"))
        self.lineEdit_ResUser.setPlaceholderText(_translate("LoginWindow", "账号"))
        self.lineEdit_ResPassword.setPlaceholderText(_translate("LoginWindow", "密码"))
        self.lineEdit_Respassword2.setPlaceholderText(_translate("LoginWindow", "确认密码"))
        self.register_bt2.setText(_translate("LoginWindow", "注册"))
        self.login_bt.setToolTip(_translate("LoginWindow", "登录"))
        self.login_bt.setText(_translate("LoginWindow", "LogIn"))
        self.register_bt.setToolTip(_translate("LoginWindow", "注册"))
        self.register_bt.setText(_translate("LoginWindow", "register"))
